--
-- Create three multi-purpose roles
-- for readers, writers, developers
-- 

CREATE ROLE ReadOnly;
GRANT CONNECT, SELECT TO ReadOnly;

CREATE ROLE ReadWrite;
GRANT CONNECT, INSERT, UPDATE, DELETE, EXECUTE TO ReadWrite;

CREATE ROLE Developer;
GRANT
     SELECT
    ,INSERT
    ,UPDATE
    ,DELETE
    ,EXECUTE
    ,CREATE TABLE
    ,CREATE VIEW
    ,CREATE PROCEDURE
    ,CREATE FUNCTION
    ,CREATE RULE
    ,CREATE DEFAULT
    ,CREATE TYPE
    ,CREATE ASSEMBLY
    ,CREATE XML SCHEMA COLLECTION
    ,CREATE SCHEMA
    ,CREATE SYNONYM
    ,CREATE AGGREGATE
    ,CREATE MESSAGE TYPE
    ,CREATE SERVICE
    ,CREATE CONTRACT
    ,CREATE REMOTE SERVICE BINDING
    ,CREATE ROUTE
    ,CREATE QUEUE
    ,CREATE SYMMETRIC KEY
    ,CREATE ASYMMETRIC KEY
    ,CREATE EXTERNAL LIBRARY
    ,CREATE FULLTEXT CATALOG
    ,CREATE CERTIFICATE
    ,CREATE DATABASE DDL EVENT NOTIFICATION
    ,CONNECT
    ,CHECKPOINT
    ,ALTER ANY SCHEMA
    ,ALTER ANY ASSEMBLY
    ,ALTER ANY DATASPACE
    ,ALTER ANY EXTERNAL LIBRARY
    ,ALTER ANY MESSAGE TYPE
    ,ALTER ANY CONTRACT
    ,ALTER ANY SERVICE
    ,ALTER ANY REMOTE SERVICE BINDING
    ,ALTER ANY ROUTE
    ,ALTER ANY FULLTEXT CATALOG
    ,ALTER ANY SYMMETRIC KEY
    ,ALTER ANY ASYMMETRIC KEY
    ,ALTER ANY CERTIFICATE
    ,REFERENCES
    ,ALTER ANY DATABASE DDL TRIGGER
    ,ALTER ANY DATABASE EVENT NOTIFICATION
    ,VIEW ANY COLUMN ENCRYPTION KEY DEFINITION
    ,VIEW ANY COLUMN MASTER KEY DEFINITION
TO Developer;

